site_name: BOU-CP
docs_dir: src

repo_url: https://github.com/boucp/boucp.github.io
edit_uri: edit/master/src/

copyright: Text is available under the <a href="https://github.com/boucp/boucp.github.io/blob/main/LICENSE">Creative Commons Attribution Share Alike 4.0 International</a> License<br/>Copyright &copy; 2023 by <a href="https://github.com/boucp">https://github.com/boucp</a>


theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box-outline
    view: material/eye
  features:
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - content.action.edit
    - content.action.view


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      tex_inline_wrap: ['$', '$']
      tex_block_wrap: ['$$', '$$']
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "hooks:copy_readme"
  